// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#ifndef MACARON_RUDIMENTAL_STRINGIZE_H
#define MACARON_RUDIMENTAL_STRINGIZE_H


#define MACARON_RUDIMENTAL_STRINGIZE_IMPLEMENTATION(...)    \
    #__VA_ARGS__
#define MACARON_RUDIMENTAL_STRINGIZE(...) \
    MACARON_RUDIMENTAL_STRINGIZE_IMPLEMENTATION(__VA_ARGS__)

#endif