// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#define CONSTRUCT    \
    MACARON_ORNAMENTAL_CONSTRUCT

#define MACARON_ORNAMENTAL_CONSTRUCT_PARAMETERS_INSPECTING  \
    INSPECT_PARAMETERS