// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#ifndef MACARON_ORNAMENTAL_TEMPLATE_H
#define MACARON_ORNAMENTAL_TEMPLATE_H

#define MACARON_ORNAMENTAL_TEMPLATE(...) \
    MACARON_ORNAMENTAL_TEMPLATE_INSPECTING<__VA_ARGS__>

#endif