// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#define MACARON_FRAGMENTAL_SHEEP_REVERSED_PREFIX_SYMBOLS  \
    SHEEP_REVERSED_PREFIX

#define MACARON_FRAGMENTAL_SHEEP_REVERSED_SUFFIX_SYMBOLS  \
    SHEEP_REVERSED_SUFFIX

#define MACARON_FRAGMENTAL_SHEEP_REVERSED_SEPARATOR_SYMBOLS  \
    SHEEP_REVERSED_SEPARATOR

#define SHEEP_REVERSED_SPROUT    \
    MACARON_FRAGMENTAL_SHEEP_REVERSED_SPROUT