// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#define MACARON_FRAGMENTAL_BINARY_SHEEP_ALTERNATIVE_PREFIX_SYMBOLS  \
    BINARY_SHEEP_ALTERNATIVE_PREFIX

#define MACARON_FRAGMENTAL_BINARY_SHEEP_ALTERNATIVE_SUFFIX_SYMBOLS  \
    BINARY_SHEEP_ALTERNATIVE_SUFFIX

#define MACARON_FRAGMENTAL_BINARY_SHEEP_ALTERNATIVE_SEPARATOR_SYMBOLS  \
    BINARY_SHEEP_ALTERNATIVE_SEPARATOR

#define BINARY_SHEEP_ALTERNATIVE_SPROUT    \
    MACARON_FRAGMENTAL_BINARY_SHEEP_ALTERNATIVE_SPROUT