// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#define MACARON_FRAGMENTAL_DOUBLE_SHEEP_REVERSED_PREFIX_SYMBOLS  \
    DOUBLE_SHEEP_REVERSED_PREFIX

#define MACARON_FRAGMENTAL_DOUBLE_SHEEP_REVERSED_MIDDLE_SYMBOLS  \
    DOUBLE_SHEEP_REVERSED_MIDDLE

#define MACARON_FRAGMENTAL_DOUBLE_SHEEP_REVERSED_SUFFIX_SYMBOLS  \
    DOUBLE_SHEEP_REVERSED_SUFFIX

#define MACARON_FRAGMENTAL_DOUBLE_SHEEP_REVERSED_SEPARATOR_SYMBOLS  \
    DOUBLE_SHEEP_REVERSED_SEPARATOR

#define DOUBLE_SHEEP_REVERSED_SPROUT    \
    MACARON_FRAGMENTAL_DOUBLE_SHEEP_REVERSED_SPROUT