// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#define MACARON_FRAGMENTAL_BINARY_SHEEP_PREFIX_SYMBOLS  \
    BINARY_SHEEP_PREFIX

#define MACARON_FRAGMENTAL_BINARY_SHEEP_SUFFIX_SYMBOLS  \
    BINARY_SHEEP_SUFFIX

#define MACARON_FRAGMENTAL_BINARY_SHEEP_SEPARATOR_SYMBOLS  \
    BINARY_SHEEP_SEPARATOR

#define BINARY_SHEEP_SPROUT    \
    MACARON_FRAGMENTAL_BINARY_SHEEP_SPROUT