// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#define MACARON_FRAGMENTAL_HORSE_REVERSED_PREFIX_SYMBOLS  \
    HORSE_REVERSED_PREFIX

#define MACARON_FRAGMENTAL_HORSE_REVERSED_SUFFIX_SYMBOLS  \
    HORSE_REVERSED_SUFFIX

#define MACARON_FRAGMENTAL_HORSE_REVERSED_SEPARATOR_SYMBOLS  \
    HORSE_REVERSED_SEPARATOR

#define HORSE_REVERSED_SPROUT    \
    MACARON_FRAGMENTAL_HORSE_REVERSED_SPROUT