// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#define MACARON_FRAGMENTAL_LLAMA_REVERSED_PREFIX_SYMBOLS  \
    LLAMA_REVERSED_PREFIX

#define MACARON_FRAGMENTAL_LLAMA_REVERSED_SUFFIX_SYMBOLS  \
    LLAMA_REVERSED_SUFFIX

#define MACARON_FRAGMENTAL_LLAMA_REVERSED_SEPARATOR_SYMBOLS  \
    LLAMA_REVERSED_SEPARATOR

#define LLAMA_REVERSED_SPROUT    \
    MACARON_FRAGMENTAL_LLAMA_REVERSED_SPROUT