// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#define MACARON_FRAGMENTAL_DOUBLE_SHEEP_PREFIX_SYMBOLS  \
    DOUBLE_SHEEP_PREFIX

#define MACARON_FRAGMENTAL_DOUBLE_SHEEP_MIDDLE_SYMBOLS  \
    DOUBLE_SHEEP_MIDDLE

#define MACARON_FRAGMENTAL_DOUBLE_SHEEP_SUFFIX_SYMBOLS  \
    DOUBLE_SHEEP_SUFFIX

#define MACARON_FRAGMENTAL_DOUBLE_SHEEP_SEPARATOR_SYMBOLS  \
    DOUBLE_SHEEP_SEPARATOR

#define DOUBLE_SHEEP_SPROUT    \
    MACARON_FRAGMENTAL_DOUBLE_SHEEP_SPROUT