// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#define MACARON_FRAGMENTAL_DOUBLE_HORSE_PREFIX_SYMBOLS  \
    DOUBLE_HORSE_PREFIX

#define MACARON_FRAGMENTAL_DOUBLE_HORSE_MIDDLE_SYMBOLS  \
    DOUBLE_HORSE_MIDDLE

#define MACARON_FRAGMENTAL_DOUBLE_HORSE_SUFFIX_SYMBOLS  \
    DOUBLE_HORSE_SUFFIX

#define MACARON_FRAGMENTAL_DOUBLE_HORSE_SEPARATOR_SYMBOLS  \
    DOUBLE_HORSE_SEPARATOR

#define DOUBLE_HORSE_SPROUT    \
    MACARON_FRAGMENTAL_DOUBLE_HORSE_SPROUT