// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#define MACARON_FRAGMENTAL_SHEEP_PREFIX_SYMBOLS  \
    SHEEP_PREFIX

#define MACARON_FRAGMENTAL_SHEEP_SUFFIX_SYMBOLS  \
    SHEEP_SUFFIX

#define MACARON_FRAGMENTAL_SHEEP_SEPARATOR_SYMBOLS  \
    SHEEP_SEPARATOR

#define SHEEP_SPROUT    \
    MACARON_FRAGMENTAL_SHEEP_SPROUT