// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#define MACARON_FRAGMENTAL_HORSE_PREFIX_SYMBOLS  \
    HORSE_PREFIX

#define MACARON_FRAGMENTAL_HORSE_SUFFIX_SYMBOLS  \
    HORSE_SUFFIX

#define MACARON_FRAGMENTAL_HORSE_SEPARATOR_SYMBOLS  \
    HORSE_SEPARATOR

#define HORSE_SPROUT    \
    MACARON_FRAGMENTAL_HORSE_SPROUT