// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#define MACARON_FRAGMENTAL_LLAMA_PREFIX_SYMBOLS  \
    LLAMA_PREFIX

#define MACARON_FRAGMENTAL_LLAMA_SUFFIX_SYMBOLS  \
    LLAMA_SUFFIX

#define MACARON_FRAGMENTAL_LLAMA_SEPARATOR_SYMBOLS  \
    LLAMA_SEPARATOR

#define LLAMA_SPROUT    \
    MACARON_FRAGMENTAL_LLAMA_SPROUT