// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#define MACARON_FRAGMENTAL_DOUBLE_LLAMA_PREFIX_SYMBOLS  \
    DOUBLE_LLAMA_PREFIX

#define MACARON_FRAGMENTAL_DOUBLE_LLAMA_MIDDLE_SYMBOLS  \
    DOUBLE_LLAMA_MIDDLE

#define MACARON_FRAGMENTAL_DOUBLE_LLAMA_SUFFIX_SYMBOLS  \
    DOUBLE_LLAMA_SUFFIX

#define MACARON_FRAGMENTAL_DOUBLE_LLAMA_SEPARATOR_SYMBOLS  \
    DOUBLE_LLAMA_SEPARATOR

#define DOUBLE_LLAMA_SPROUT    \
    MACARON_FRAGMENTAL_DOUBLE_LLAMA_SPROUT