// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#define MACARON_FRAGMENTAL_ALKANE_PREFIX_SYMBOLS  \
    ALKANE_PREFIX

#define MACARON_FRAGMENTAL_ALKANE_CARBON_SYMBOLS  \
    ALKANE_CARBON

#define MACARON_FRAGMENTAL_ALKANE_SUFFIX_SYMBOLS  \
    ALKANE_SUFFIX

#define MACARON_FRAGMENTAL_ALKANE_SEPARATOR_SYMBOLS  \
    ALKANE_SEPARATOR

#define ALKANE_SPROUT    \
    MACARON_FRAGMENTAL_ALKANE_SPROUT