// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#undef MACARON_FRAGMENTAL_DOUBLE_HORSE_PREFIX_SYMBOLS
#undef MACARON_FRAGMENTAL_DOUBLE_HORSE_MIDDLE_SYMBOLS
#undef MACARON_FRAGMENTAL_DOUBLE_HORSE_SUFFIX_SYMBOLS
#undef MACARON_FRAGMENTAL_DOUBLE_HORSE_SEPARATOR_SYMBOLS
#undef DOUBLE_HORSE_SPROUT