// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#undef MACARON_FRAGMENTAL_DOUBLE_SHEEP_PREFIX_SYMBOLS
#undef MACARON_FRAGMENTAL_DOUBLE_SHEEP_MIDDLE_SYMBOLS
#undef MACARON_FRAGMENTAL_DOUBLE_SHEEP_SUFFIX_SYMBOLS
#undef MACARON_FRAGMENTAL_DOUBLE_SHEEP_SEPARATOR_SYMBOLS
#undef DOUBLE_SHEEP_SPROUT