// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#undef MACARON_FRAGMENTAL_HORSE_PREFIX_SYMBOLS
#undef MACARON_FRAGMENTAL_HORSE_SUFFIX_SYMBOLS
#undef MACARON_FRAGMENTAL_HORSE_SEPARATOR_SYMBOLS
#undef HORSE_SPROUT