// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#undef MACARON_FRAGMENTAL_LLAMA_REVERSED_PREFIX_SYMBOLS
#undef MACARON_FRAGMENTAL_LLAMA_REVERSED_SUFFIX_SYMBOLS
#undef MACARON_FRAGMENTAL_LLAMA_REVERSED_SEPARATOR_SYMBOLS
#undef LLAMA_REVERSED_SPROUT