// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#define MACARON_FRAGMENTAL_ALKANE_PREFIX_SYMBOLS
#define MACARON_FRAGMENTAL_ALKANE_CARBON_SYMBOLS  \
    1
#define MACARON_FRAGMENTAL_ALKANE_SUFFIX_SYMBOLS
#define MACARON_FRAGMENTAL_ALKANE_SEPARATOR_SYMBOLS  \
    ,