// Copyright 2024 Feng Mofan
// SPDX-License-Identifier: Apache-2.0

#undef MACARON_FRAGMENTAL_ALKANE_PREFIX_SYMBOLS
#undef MACARON_FRAGMENTAL_ALKANE_CARBON_SYMBOLS
#undef MACARON_FRAGMENTAL_ALKANE_SUFFIX_SYMBOLS
#undef MACARON_FRAGMENTAL_ALKANE_SEPARATOR_SYMBOLS